#!/usr/bin/env python3

from qrcode import QRCode, ERROR_CORRECT_L
import sys

def print_qr(data: str) -> None:
    qr = QRCode(
        version=1,
        error_correction=ERROR_CORRECT_L,
        box_size=10,
        border=4,
    )
    qr.add_data(data)
    qr.make(fit=True)

    qr.print_tty()

def main() -> None:
    if len(sys.argv) > 1:
        data = ' '.join(sys.argv[1:]) # read from argv if arguments were given
    else:
        data = sys.stdin.read() # else read from stdin
    print_qr(data)


if __name__ == "__main__":
    main()
